name: Release
on:
  push:
    branches: [ "mtcute" ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Sample Files
        run: |
          mkdir -p samples
          for i in {1..8}; do
            echo "Sample file $i" > "samples/sample$i.txt"
          done


      - name: Upload to Telegram
        uses: nekogram/upload-with-mtcute@e196262c35b722c4c8eac79c835ec6dbd109e4b8
        with:
          api-id: ${{ secrets.API_ID }}
          api-hash: ${{ secrets.API_HASH }}
          bot-token: ${{ secrets.RELEASE_BOT_TOKEN }}
          chat-id: ${{ secrets.RELEASE_CHANNEL_ID }}
          files: samples/*